[features]
seeds = false
skip-lint = false
[programs.localnet]
token_program = "5EyzFuQFafP4Mv1JPqi9EFzaEJUXCRBb5GPvF5YByuU6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/agathokako/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
